#!/bin/sh

# Check if the PYFILE environment variable is set
if [ -z "$PYCODE" ]; then
  echo "Error: PYCODE environment variable is not set."
  exit 1
fi

# Run the Python code specified in PYCODE
python3 -c "$PYCODE"

